[package]
name = "bevy_metrics_dashboard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_egui = "0.24.0"
egui_plot = "0.24.2"
float-ord = "0.3.2"
fuzzy-matcher = "0.3.7"
metrics = "0.22.0"
metrics-util = "0.16.0"
smallvec = "1.13.1"

[dependencies.bevy]
version = "0.12.1"
default-features = false
features = ["multi-threaded"]

[dev-dependencies.bevy]
version = "0.12.1"
default-features = false
features = ["bevy_winit", "x11"]
